In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
import seaborn as sns
import scipy.stats as stats

Data prep

In [2]:
filename = "2021-2022_NBA_Player_Stats.csv"
df = pd.read_csv(filename,index_col=0, encoding = "ISO-8859-1",  sep=';')
df.head(9)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
Rk,,,,,,,,,,,,,,,,,,,,,
1,Precious Achiuwa,C,22,TOR,48,23,23.1,3.1,7.3,0.423,...,0.579,2.2,4.7,6.9,1.1,0.5,0.6,1.0,2.0,7.5
2,Steven Adams,C,28,MEM,56,55,26.1,2.8,5.0,0.546,...,0.556,4.5,5.1,9.6,3.2,0.9,0.7,1.6,1.9,7.0
3,Bam Adebayo,C,24,MIA,33,33,33.0,7.2,13.6,0.527,...,0.764,2.8,7.4,10.2,3.5,1.5,0.6,2.9,3.2,18.7
4,Santi Aldama,PF,21,MEM,27,0,10.3,1.4,3.6,0.381,...,0.600,0.9,1.5,2.4,0.5,0.1,0.3,0.3,1.0,3.3
5,LaMarcus Aldridge,C,36,BRK,38,11,22.8,5.8,10.5,0.558,...,0.844,1.6,4.2,5.8,0.8,0.3,1.1,1.0,1.7,13.7
6,Nickeil Alexander-Walker,SG,23,TOT,52,19,25.4,4.6,12.2,0.374,...,0.722,0.7,2.5,3.2,2.7,0.8,0.4,1.6,1.7,12.3
6,Nickeil Alexander-Walker,SG,23,NOP,50,19,26.3,4.7,12.6,0.375,...,0.722,0.7,2.6,3.3,2.8,0.8,0.4,1.7,1.8,12.8
6,Nickeil Alexander-Walker,SG,23,UTA,2,0,2.5,0.0,0.5,0.000,...,0.000,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,0.0
7,Grayson Allen,SG,26,MIL,49,48,28.0,4.0,9.4,0.425,...,0.857,0.5,2.9,3.4,1.5,0.8,0.3,0.6,1.4,11.5

In [3]:
df.loc[df["Player"] == "Nikola Joki?", "Player"] = 'Nikola Jokic'
df.loc[df["Player"] == "Luka Don?i?", "Player"] = 'Luka Doncic'

In [4]:
all_star = [0]*734

In [5]:
df['ALLSTAR'] = all_star

In [6]:
df.loc[df['Player'].isin(['Trae Young', 'DeMar DeRozan', 'Joel Embiid', 'Kevin Durant', 'Giannis Antetokounmpo', 'LaMelo Ball', 
'Darius Garland', 'James Harden', 'Zach LaVine', 'Fred VanVleet', 'Jimmy Butler', 'Khris Middleton', 'Jayson Tatum', 'Jarrett Allen',
'Stephen Curry', 'Ja Morant', 'Nikola Jokic', 'LeBron James', 'Andrew Wiggins', 'Devin Booker', 'Luka Doncic', 'Donovan Mitchell', 
'Dejounte Murray', 'Chris Paul', 'Draymond Green', 'Rudy Gobert', 'Karl-Anthony Towns']), "ALLSTAR"] = 1

In [7]:
df = df.drop_duplicates(subset=['Player'])
df[df['Tm'] == 'TOT']

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,ALLSTAR
Rk,,,,,,,,,,,,,,,,,,,,,
6,Nickeil Alexander-Walker,SG,23,TOT,52,19,25.4,4.6,12.2,0.374,...,0.7,2.5,3.2,2.7,0.8,0.4,1.6,1.7,12.3,0
10,Justin Anderson,SF,28,TOT,6,0,12.8,1.0,3.2,0.316,...,0.3,1.3,1.7,1.5,0.3,0.2,0.5,1.5,3.5,0
23,Marvin Bagley III,PF,22,TOT,32,17,21.9,3.8,8.2,0.460,...,2.3,4.9,7.2,0.6,0.3,0.3,0.7,1.6,9.2,0
44,D?vis Bert?ns,PF,29,TOT,35,0,14.7,1.8,5.1,0.358,...,0.2,1.6,1.8,0.5,0.3,0.2,0.4,1.6,5.9,0
72,Charlie Brown Jr.,SG,24,TOT,19,2,9.1,0.5,2.1,0.256,...,0.7,0.9,1.7,0.3,0.5,0.2,0.3,0.9,1.6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,Brad Wanamaker,PG,32,TOT,23,2,13.9,1.2,3.3,0.364,...,0.3,1.4,1.7,2.4,0.3,0.3,1.0,2.0,3.6,0
560,Tremont Waters,PG,24,TOT,3,0,16.7,1.3,4.7,0.286,...,0.0,1.3,1.3,2.3,1.7,0.0,1.3,1.3,3.3,0
566,Derrick White,SG,27,TOT,53,49,30.3,4.9,11.6,0.423,...,0.5,3.0,3.6,5.5,1.1,0.9,1.8,2.4,14.2,0
581,Justise Winslow,SF,25,TOT,43,6,15.5,2.1,4.7,0.451,...,0.9,3.2,4.1,1.7,0.7,0.5,1.0,1.3,5.3,0
588,Thaddeus Young,PF,33,TOT,28,1,14.4,2.9,5.1,0.570,...,1.6,2.1,3.6,2.2,0.9,0.3,1.2,1.5,6.1,0

In [8]:
df[df['G']<10]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,ALLSTAR
Rk,,,,,,,,,,,,,,,,,,,,,
10,Justin Anderson,SF,28,TOT,6,0,12.8,1.0,3.2,0.316,...,0.3,1.3,1.7,1.5,0.3,0.2,0.5,1.5,3.5,0
20,Joel Ayayi,SG,21,WAS,7,0,2.9,0.1,0.9,0.167,...,0.1,0.3,0.4,0.6,0.0,0.0,0.0,0.0,0.3,0
29,Cat Barber,PG,27,ATL,3,0,4.3,0.0,1.3,0.000,...,0.3,0.7,1.0,1.0,0.0,0.0,0.3,0.3,0.0,0
34,Paris Bass,SF,26,PHO,2,0,3.5,1.0,3.0,0.333,...,1.0,1.0,2.0,0.0,0.5,0.0,1.0,1.0,3.0,0
42,Jordan Bell,C,27,CHI,1,0,2.0,0.0,0.0,0.000,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,2.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576,Patrick Williams,PF,20,CHI,5,5,25.0,2.6,4.6,0.565,...,0.2,2.0,2.2,0.6,0.6,0.4,0.4,1.8,6.6,0
579,D.J. Wilson,PF,25,TOR,3,1,16.0,2.7,3.7,0.727,...,0.3,4.3,4.7,1.3,1.7,0.3,0.7,1.7,8.0,0
582,Cassius Winston,PG,23,WAS,4,0,5.8,0.8,1.5,0.500,...,0.0,0.0,0.0,1.0,0.0,0.0,0.3,1.0,2.5,0
586,McKinley Wright IV,PG,23,MIN,3,0,3.0,0.7,1.0,0.667,...,0.0,0.0,0.0,0.3,0.0,0.0,0.3,0.3,1.7,0
587,Moses Wright,PF,23,LAC,1,0,1.0,0.0,0.0,0.000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0

In [9]:
df = df.drop(df[df['G'] < 10].index)

In [11]:
df.describe()

,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,ALLSTAR
count,469.000000,469.000000,469.000000,469.000000,469.000000,469.000000,469.000000,469.000000,469.000000,469.000000,...,469.000000,469.000000,469.000000,469.000000,469.000000,469.000000,469.000000,469.000000,469.000000,469.000000
mean,25.948827,38.929638,18.646055,21.002132,3.454158,7.596802,0.451567,1.045416,3.010661,0.309463,...,0.934328,2.980810,3.913433,2.080597,0.663539,0.426652,1.147335,1.737953,9.355224,0.057569
std,4.274945,13.437786,19.889505,9.020596,2.270973,4.841943,0.089488,0.879300,2.342294,0.126868,...,0.759410,1.842325,2.407514,1.879030,0.394098,0.387786,0.842195,0.715196,6.276622,0.233176
min,19.000000,10.000000,0.000000,2.800000,0.100000,0.600000,0.125000,0.000000,0.000000,0.000000,...,0.000000,0.200000,0.300000,0.000000,0.000000,0.000000,0.000000,0.100000,0.300000,0.000000
25%,23.000000,28.000000,1.000000,13.900000,1.800000,3.900000,0.400000,0.300000,1.100000,0.278000,...,0.400000,1.600000,2.100000,0.800000,0.400000,0.200000,0.600000,1.200000,4.700000,0.000000
50%,25.000000,42.000000,9.000000,20.300000,2.900000,6.300000,0.444000,0.800000,2.500000,0.333000,...,0.700000,2.600000,3.400000,1.400000,0.600000,0.300000,0.900000,1.700000,7.700000,0.000000
75%,29.000000,50.000000,38.000000,28.800000,4.700000,10.500000,0.492000,1.600000,4.700000,0.375000,...,1.200000,3.800000,4.900000,2.700000,0.900000,0.500000,1.500000,2.300000,13.000000,0.000000
max,38.000000,60.000000,60.000000,38.400000,11.000000,21.400000,0.762000,4.600000,12.300000,1.000000,...,4.500000,11.300000,14.800000,10.700000,2.000000,2.800000,4.800000,3.700000,29.400000,1.000000

Above average points "B"

In [10]:
print(df['PTS'].mean())

9.355223880597023

In [12]:
print(df[df['PTS'] > df['PTS'].mean()].shape[0])

183

+b

In [28]:
b = df[df['PTS'] > df['PTS'].mean()].shape[0]/df['PTS'].shape[0]
print(b)

0.39019189765458423

-b

In [29]:
print(1-b)

0.6098081023454158

2PT% > 55% "D"

In [14]:
print(df[df['2P%'] > 0.55].shape[0])

154

+d

In [30]:
d = df[df['2P%'] > 0.55].shape[0]/df['2P%'].shape[0]
print(d)

0.3283582089552239

-d

In [31]:
print(1-d)

0.6716417910447761

3PT% > 38% "T"

In [17]:
print(df[df['3P%'] > 0.38].shape[0])

100

+t

In [32]:
t = df[df['3P%'] > 0.38].shape[0]/df['3P%'].shape[0]
print(t)

0.21321961620469082

-t

In [33]:
print(1-t)

0.7867803837953091

Is starter (GS/G > 50%) "S"

In [24]:
print(df[df['GS']/df['G'] > 0.5].shape[0])

169

+s

In [40]:
s = df[df['GS']/df['G'] > 0.5].shape[0]/df['G'].shape[0]
print(s)

0.3603411513859275

-s

In [41]:
print(1-s)

0.6396588486140725

Is ALLSTAR "A"

In [25]:
print(df[df['ALLSTAR'] == 1].shape[0])

27

+a

In [36]:
a = df[df['ALLSTAR'] == 1].shape[0]/df['ALLSTAR'].shape[0]
print(a)

0.057569296375266525

-a

In [37]:
print(1-a)

0.9424307036247335

Intersections

D âˆ© T

In [44]:
df.loc[(df['2P%'] > 0.55) & (df['3P%'] > 0.38)].shape[0]

33

In [45]:
print(df.loc[(df['2P%'] > 0.55) & (df['3P%'] > 0.38)].shape[0]/df['3P%'].shape[0])

0.07036247334754797

B âˆ© S

In [42]:
df.loc[(df['PTS'] > df['PTS'].mean()) & (df['GS']/df['G'] > 0.5)].shape[0]

136

In [43]:
print(df.loc[(df['PTS'] > df['PTS'].mean()) & (df['GS']/df['G'] > 0.5)].shape[0]/df['PTS'].shape[0])

0.2899786780383795

P(B,D,T)

In [48]:
bdt = df.loc[(df['PTS'] > df['PTS'].mean()) & (df['2P%'] > 0.55) & (df['3P%'] > 0.38)].shape[0]/df['PTS'].shape[0]
print('bdt: ', bdt)
bd_t = df.loc[(df['PTS'] > df['PTS'].mean()) & (df['2P%'] > 0.55) & (df['3P%'] <= 0.38)].shape[0]/df['PTS'].shape[0]
print('bd_t: ', bd_t)
b_dt = df.loc[(df['PTS'] > df['PTS'].mean()) & (df['2P%'] <= 0.55) & (df['3P%'] > 0.38)].shape[0]/df['PTS'].shape[0]
print('b_dt: ', b_dt)
b_d_t = df.loc[(df['PTS'] > df['PTS'].mean()) & (df['2P%'] <= 0.55) & (df['3P%'] <= 0.38)].shape[0]/df['PTS'].shape[0]
print('b_d_t: ', b_d_t)
_bdt = df.loc[(df['PTS'] <= df['PTS'].mean()) & (df['2P%'] > 0.55) & (df['3P%'] > 0.38)].shape[0]/df['PTS'].shape[0]
print('_bdt: ', _bdt)
_bd_t = df.loc[(df['PTS'] <= df['PTS'].mean()) & (df['2P%'] > 0.55) & (df['3P%'] <= 0.38)].shape[0]/df['PTS'].shape[0]
print('_bd_t: ', _bd_t)
_b_dt = df.loc[(df['PTS'] <= df['PTS'].mean()) & (df['2P%'] <= 0.55) & (df['3P%'] > 0.38)].shape[0]/df['PTS'].shape[0]
print('_b_dt: ', _b_dt)
_b_d_t = df.loc[(df['PTS'] <= df['PTS'].mean()) & (df['2P%'] <= 0.55) & (df['3P%'] <= 0.38)].shape[0]/df['PTS'].shape[0]
print('_b_d_t: ', _b_d_t)

bdt:  0.021321961620469083
bd_t:  0.07889125799573561
b_dt:  0.07889125799573561
b_d_t:  0.21108742004264391
_bdt:  0.04904051172707889
_bd_t:  0.1791044776119403
_b_dt:  0.06396588486140725
_b_d_t:  0.31769722814498935

P(D,T)

In [49]:
dt = df.loc[(df['2P%'] > 0.55) & (df['3P%'] > 0.38)].shape[0]/df['3P%'].shape[0]
print('dt: ', dt)
d_t = df.loc[(df['2P%'] > 0.55) & (df['3P%'] <= 0.38)].shape[0]/df['3P%'].shape[0]
print('d_t: ', d_t)
_dt = df.loc[(df['2P%'] <= 0.55) & (df['3P%'] > 0.38)].shape[0]/df['3P%'].shape[0]
print('_dt: ', _dt)
_d_t = df.loc[(df['2P%'] <= 0.55) & (df['3P%'] <= 0.38)].shape[0]/df['3P%'].shape[0]
print('_d_t: ', _d_t)

dt:  0.07036247334754797
d_t:  0.2579957356076759
_dt:  0.14285714285714285
_d_t:  0.5287846481876333